waypoints:

  1:
    nome: "Ponto 1"
    x: 7.323
    y: 6.041
    yaw: -3.141593

  2:
    nome: "Ponto 2"
    x: 7.231
    y: 1.968
    yaw: 3.017
     
  3:
    nome: "Ponto 3"
    x: 7.369
    y: -1.968
    yaw: 3.141593

  4:
    nome: "Ponto 4"
    x: 7.323
    y: -5.996
    yaw: 0.0

  5:
    nome: "Ponto 5"
    x: 3.250
    y: 6.041
    yaw: 3.141593

  6:
    nome: "Ponto 6"
    x: 3.250
    y: 1.968
    yaw: 3.141593

  7:
    nome: "Ponto 7"
    x: 3.295
    y: -1.922
    yaw: -3.090

  8:
    nome: "Ponto 8"
    x: 3.250
    y: -5.996
    yaw: -3.141593

  9:
    nome: "Ponto 9"
    x: -0.808
    y: 6.037
    yaw: -3.136

  10:
    nome: "Ponto 10"
    x: -0.788
    y: 2.056
    yaw: -3.090

  11:
    nome: "Ponto 11"
    x: -0.814
    y: -1.972
    yaw: -3.136

  12:
    nome: "Ponto 12"
    x: -0.840
    y: -6.000
    yaw: -3.136

  13:
    nome: "Ponto 13"
    x: -4.790
    y: 6.063
    yaw: -3.136

  14:
    nome: "Ponto 14"
    x: -4.816
    y: 2.036
    yaw: -3.098

  15:
    nome: "Ponto 15"
    x: -4.841
    y: -2.038
    yaw: -3.136

  16:
    nome: "Ponto 16"
    x: -4.684
    y: -5.973
    yaw: -3.090
